name: Analyze, Test and Build

on:
  Push:
    branches:
    - master
  pull_request:

jobs:
  lint:
    name: Alayze the code
    runs_on: ubuntu_latest
    steps:
      - name: Clone flutter repository from stable channel with 3.3.10 version
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.10'
          channel:  'stable'

      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Update dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze 
      
  